spring:
  datasource:
    # same comment as at docker-compose.yml, should split to profiles and use env variables
    url: jdbc:postgresql://localhost:5432/yawp
    username: user
    password: password

  flyway:
    user: user
    password: password
    url: jdbc:postgresql://localhost:5432/yawp
    locations: classpath:db/migration
    enabled: true

security:
  jwt:
    token:
      lifetime: 86400 # 24 hours
      secretKey: 08=-=(_KSDFodsf_+(_($_+1jd@$u- # should be changed to something more secure and retrieved from env variables
