spring:
  datasource:
    # same comment as at docker-compose.yml, should split to profiles and use env variables
    url: jdbc:postgresql://localhost:5432/yawp
    username: user
    password: password
    #    show hibernate sql
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  flyway:
    user: user
    password: password
    url: jdbc:postgresql://localhost:5432/yawp
    locations: classpath:db/migration
    enabled: true

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: supersecret!
      timeout: 60000


security:
  jwt:
    token:
      lifetime: 86400000 # 24 hours
      secretKey: 08=-=(_KSDFodsf_+(_($_+1jd@$u- # should be changed to something more secure and retrieved from env variables


api:
  version: 1
  base: /api/v1
  description: Users API
  server:
    url: http://localhost:8080/
#    eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huIiwiZXhwIjo5MjIzMzcyMDM2ODU0Nzc1LCJpYXQiOjE2NzIzMjM2NDksInVzZXJJZCI6ImY5NTEyZjI4LWFkMmMtNGIwYS1hOTA5LTY4OTdkOWJiNGI2NiJ9.DhdpF-ZZkGfU4Bp7DSuWJHPBTFAb8nL0sMGgkLhYHlM: